/**
 * Supplies catalog — prices (AUD) must match `server/lib/supplies-catalog.js`.
 *
 * Cover art: `public/supplies/{id}.png` (transparent PNGs). Generate with:
 *   npm run generate:supply-images
 * Requires `OPENAI_API_KEY` and a GPT Image model (e.g. gpt-image-1).
 */

import type { HardwareProduct } from './hardwareCatalog'

export type SupplyCategoryId = 'cleaning' | 'packing'

export type SupplyProduct = HardwareProduct & {
  categoryId: SupplyCategoryId
  coverImageUrl: string
}

type SupplyProductDef = Omit<SupplyProduct, 'coverImageUrl'>

const SUPPLY_PRODUCT_DEFS: readonly SupplyProductDef[] = [
  {
    id: 'sup-clean-pro-kit',
    sku: 'SUPPLY_CLEAN_PRO_KIT',
    title: 'Pro clean starter',
    subtitle: 'Spray bottles · cloths · gloves',
    priceAud: 48,
    previewStyle: 'emerald',
    categoryId: 'cleaning',
    specs: ['3× 500 ml bottles', '12× microfibre cloths', 'Nitrile gloves (M)'],
    description: 'Reset kitchens and baths between jobs.',
  },
  {
    id: 'sup-clean-floor',
    sku: 'SUPPLY_CLEAN_FLOOR_SYS',
    title: 'Hard-floor system',
    subtitle: 'Mop · pads · neutral cleaner',
    priceAud: 72,
    previewStyle: 'slate',
    categoryId: 'cleaning',
    specs: ['Flat mop + 4 pads', '2 L cleaner', 'Grout brush'],
    description: 'Low-streak routine for timber and tile.',
  },
  {
    id: 'sup-clean-stick-vac',
    sku: 'SUPPLY_CLEAN_STICK_VAC',
    title: 'Stick vacuum kit',
    subtitle: 'Crevice tool · hard floors',
    priceAud: 118,
    previewStyle: 'slate',
    categoryId: 'cleaning',
    specs: ['Motorised floor head', 'HEPA filter', '45 min runtime'],
    description: 'Quick touch-ups between full cleans.',
  },
  {
    id: 'sup-clean-spray-trio',
    sku: 'SUPPLY_CLEAN_SPRAY_TRIO',
    title: 'Surface spray trio',
    subtitle: 'Glass · bath · degrease',
    priceAud: 36,
    previewStyle: 'emerald',
    categoryId: 'cleaning',
    specs: ['3× 750 ml triggers', 'Colour-coded caps', 'QR SDS'],
    description: 'Grab the right bottle at a glance.',
  },
  {
    id: 'sup-pack-move-kit',
    sku: 'SUPPLY_PACK_MOVE_KIT_S',
    title: 'Apartment pack kit',
    subtitle: 'Boxes · tape · bubble wrap',
    priceAud: 89,
    previewStyle: 'violet',
    categoryId: 'packing',
    specs: ['15 small + 10 medium cartons', '2 tape rolls', '20 m wrap'],
    description: 'Sized for 1–2 bedroom pack-outs.',
  },
  {
    id: 'sup-pack-fragile',
    sku: 'SUPPLY_PACK_FRAGILE',
    title: 'Fragile cell kit',
    subtitle: 'Dish cells · corners · tape',
    priceAud: 56,
    previewStyle: 'slate',
    categoryId: 'packing',
    specs: ['8 dish cells', '40 corner guards', 'Glassine roll'],
    description: 'Protects glass on local moves.',
  },
  {
    id: 'sup-pack-tape-kit',
    sku: 'SUPPLY_PACK_TAPE_KIT',
    title: 'Tape & dispenser',
    subtitle: 'Fibre tape · cutter · refills',
    priceAud: 42,
    previewStyle: 'violet',
    categoryId: 'packing',
    specs: ['Quiet dispenser', '2× 48 mm rolls', 'Fragile print roll'],
    description: 'Seal cartons fast and clean.',
  },
  {
    id: 'sup-pack-pad-blanket',
    sku: 'SUPPLY_PACK_PAD_BLANKET',
    title: 'Furniture pad bundle',
    subtitle: 'Quilted pads · edge quilts',
    priceAud: 78,
    previewStyle: 'slate',
    categoryId: 'packing',
    specs: ['4 large pads', '2 door jamb quilts', 'Washable'],
    description: 'Polished timber and glass in tight stairs.',
  },
  {
    id: 'sup-clean-micro-bulk',
    sku: 'SUPPLY_CLEAN_MICRO_BULK',
    title: 'Microfibre bulk pack',
    subtitle: '24 cloths · colour bands',
    priceAud: 34,
    previewStyle: 'emerald',
    categoryId: 'cleaning',
    specs: ['24× 30×30 cm', 'Lint-light weave', 'Machine wash'],
    description: 'Rotate colours by room so you never cross-contaminate.',
  },
  {
    id: 'sup-clean-gloves-nitrile',
    sku: 'SUPPLY_CLEAN_GLOVES_NITRILE',
    title: 'Nitrile gloves (L)',
    subtitle: '100 pack · powder-free',
    priceAud: 28,
    previewStyle: 'emerald',
    categoryId: 'cleaning',
    specs: ['5 mil', 'Textured grip', 'Latex-free'],
    description: 'Comfortable for longer deep cleans.',
  },
  {
    id: 'sup-clean-degrease',
    sku: 'SUPPLY_CLEAN_DEGREASE',
    title: 'Kitchen degreaser',
    subtitle: '2 L refill · citrus',
    priceAud: 22,
    previewStyle: 'emerald',
    categoryId: 'cleaning',
    specs: ['Concentrate', 'Range hood safe', 'Food-prep adjacent'],
    description: 'Cuts through cooktop film without harsh fumes.',
  },
  {
    id: 'sup-clean-toilet',
    sku: 'SUPPLY_CLEAN_TOILET_SYS',
    title: 'Bath & toilet kit',
    subtitle: 'Bowl · brush · lime scale',
    priceAud: 31,
    previewStyle: 'slate',
    categoryId: 'cleaning',
    specs: ['Angled brush', '750 ml bowl cleaner', 'Grout pen'],
    description: 'Everything for a quick bathroom reset.',
  },
  {
    id: 'sup-clean-glass',
    sku: 'SUPPLY_CLEAN_GLASS_PRO',
    title: 'Glass & mirror pro',
    subtitle: 'Squeegee · 1 L refill',
    priceAud: 26,
    previewStyle: 'slate',
    categoryId: 'cleaning',
    specs: ['Streak-free formula', 'Rubber blade', 'Extension pole clip'],
    description: 'Large sliders and shower screens in fewer passes.',
  },
  {
    id: 'sup-clean-odour',
    sku: 'SUPPLY_CLEAN_ODOUR_NEUT',
    title: 'Odour neutraliser',
    subtitle: 'Spray · 500 ml × 2',
    priceAud: 19,
    previewStyle: 'emerald',
    categoryId: 'cleaning',
    specs: ['Enzyme base', 'Pet-safe when dry', 'Low scent'],
    description: 'For turnovers where smell matters as much as shine.',
  },
  {
    id: 'sup-clean-mop-pads',
    sku: 'SUPPLY_CLEAN_MOP_PADS_8',
    title: 'Mop pad refill (8)',
    subtitle: 'Microfibre · loop backing',
    priceAud: 24,
    previewStyle: 'slate',
    categoryId: 'cleaning',
    specs: ['Fits Fetch flat mop', 'Wash 60×', 'Colour-coded tags'],
    description: 'Keep a fresh pad on hand every day of the week.',
  },
  {
    id: 'sup-pack-wardrobe',
    sku: 'SUPPLY_PACK_WARDROBE_BOX',
    title: 'Wardrobe cartons (3)',
    subtitle: 'Bar included · tall',
    priceAud: 64,
    previewStyle: 'violet',
    categoryId: 'packing',
    specs: ['120 cm hanging space', 'Reinforced base', 'Perforated vents'],
    description: 'Suits dresses and coats without folding creases.',
  },
  {
    id: 'sup-pack-paper',
    sku: 'SUPPLY_PACK_PAPER_10KG',
    title: 'Packing paper bundle',
    subtitle: '10 kg news offcuts',
    priceAud: 38,
    previewStyle: 'slate',
    categoryId: 'packing',
    specs: ['Ink-light', 'Acid-free option mix', 'Easy tear'],
    description: 'Wrap glass and ceramics before cells.',
  },
  {
    id: 'sup-pack-stretch',
    sku: 'SUPPLY_PACK_STRETCH_WRAP',
    title: 'Stretch wrap hand roll',
    subtitle: '400 mm × 300 m',
    priceAud: 29,
    previewStyle: 'violet',
    categoryId: 'packing',
    specs: ['Extended core', 'Quiet unwind', 'Bundling sofas'],
    description: 'Hold doors and drawers closed on dollies.',
  },
  {
    id: 'sup-pack-markers',
    sku: 'SUPPLY_PACK_MARKER_SET',
    title: 'Room marker set',
    subtitle: '12 permanent · labels',
    priceAud: 16,
    previewStyle: 'violet',
    categoryId: 'packing',
    specs: ['Colour per room', '250 adhesive flags', 'Smear-resistant'],
    description: 'Crew unloads to the right zone first time.',
  },
  {
    id: 'sup-pack-mattress',
    sku: 'SUPPLY_PACK_MATTRESS_BAG',
    title: 'Mattress bag (queen)',
    subtitle: 'Heavy poly · zip',
    priceAud: 18,
    previewStyle: 'slate',
    categoryId: 'packing',
    specs: ['6 mil', 'Full enclosure', 'Reusable once'],
    description: 'Keeps fabric dry in light rain between truck and lift.',
  },
  {
    id: 'sup-pack-rope',
    sku: 'SUPPLY_PACK_ROPE_TIE',
    title: 'Tie-down rope kit',
    subtitle: '15 m × 2 · carabiners',
    priceAud: 22,
    previewStyle: 'slate',
    categoryId: 'packing',
    specs: ['Braided poly', 'Soft loops', '200 kg WLL note'],
    description: 'Anchor tall stacks in the truck body.',
  },
  {
    id: 'sup-pack-bubble-narrow',
    sku: 'SUPPLY_PACK_BUBBLE_NARROW',
    title: 'Bubble roll (narrow)',
    subtitle: '30 cm × 50 m',
    priceAud: 35,
    previewStyle: 'violet',
    categoryId: 'packing',
    specs: ['10 mm bubbles', 'Perforated every 30 cm', 'Frames & art'],
    description: 'Easier to wrap long items than wide rolls.',
  },
  {
    id: 'sup-pack-blade',
    sku: 'SUPPLY_PACK_UTILITY_BLADES',
    title: 'Utility blades (20)',
    subtitle: 'Standard trapezoid',
    priceAud: 12,
    previewStyle: 'slate',
    categoryId: 'packing',
    specs: ['Dispenser compatible', 'Carbon steel', 'Storage case'],
    description: 'Fresh blade per job for clean carton cuts.',
  },
]

export const SUPPLY_PRODUCTS: readonly SupplyProduct[] = SUPPLY_PRODUCT_DEFS.map((row) => ({
  ...row,
  coverImageUrl: `/supplies/${row.id}.png`,
}))

export function getSupplyProductsByCategory(id: SupplyCategoryId): readonly SupplyProduct[] {
  return SUPPLY_PRODUCTS.filter((p) => p.categoryId === id)
}
