-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgFNMrgA8v2yKofylO
bL3erbVIduJHfMDemFW3X/kUbDigCgYIKoZIzj0DAQehRANCAATnawhS3Lbjt8GT
mhNJJIGBNXD5F3WNT31zApDyABDomjp7Cve+m+4Mt3Tn03SnMmEch/tiXR0a+Jot
1jRcVMTi
-----END PRIVATE KEY-----