import type { DropCategoryId, DropReel, DropRegionCode } from './types'

/** Verified Fetch Drops admin — used for official promos (mirrors paid boost slots). */
export const FETCH_DROPS_OFFICIAL_AUTHOR_ID = 'fetch_official'

export const FETCH_DROPS_OFFICIAL_HANDLE = '@Fetch'

export const DROP_CATEGORY_LABELS: Record<DropCategoryId, string> = {
  supplies: 'Supplies',
  local_pickup: 'Local pickup',
  b2b: 'Business',
  promo: 'Promo',
  community: 'Community',
  services: 'Services',
}

export const DROP_REGION_LABELS: Record<DropRegionCode, string> = {
  SEQ: 'South East QLD',
  NSW: 'New South Wales',
  VIC: 'Victoria',
  AU_WIDE: 'Australia',
}

/** Demo “active users” for smart view estimates until analytics exists. */
export const DROPS_ESTIMATED_MAU = 12_400

export const CURATED_DROP_REELS: readonly DropReel[] = [
  {
    id: 'demo-photos-supplies',
    imageUrls: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    ],
    mediaKind: 'images',
    title: 'Photo drop — gear & audio (swipe)',
    seller: '@FetchSupply',
    authorId: 'demo_fetch_supply',
    priceLabel: 'From $29',
    blurb: 'Swipe photos · same-day zone · mobile-first',
    likes: 12400,
    growthVelocityScore: 1.22,
    watchTimeMsSeed: 900_000,
    categories: ['supplies', 'promo'],
    region: 'SEQ',
    commerce: { kind: 'marketplace_product', productId: 'sup-drink-soft-case' },
  },
  {
    id: 'demo-1',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    title: 'Limited drop — thermal bottle',
    seller: '@FetchSupply',
    authorId: 'demo_fetch_supply',
    priceLabel: '$42',
    blurb: 'Shop in app · same-day zone',
    likes: 18200,
    growthVelocityScore: 1.15,
    watchTimeMsSeed: 1_800_000,
    categories: ['supplies', 'promo'],
    region: 'SEQ',
    commerce: { kind: 'marketplace_product', productId: 'sup-drink-soft-case' },
  },
  {
    id: 'demo-2',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    title: 'Local maker — hand soap trio',
    seller: '@BrisbaneBasics',
    authorId: 'demo_brisbane_basics',
    priceLabel: '$28',
    blurb: 'Free pickup · Sat market',
    likes: 9600,
    growthVelocityScore: 1.42,
    watchTimeMsSeed: 2_200_000,
    categories: ['local_pickup', 'community'],
    region: 'SEQ',
    commerce: { kind: 'marketplace_product', productId: 'sup-drink-sparkling-12' },
  },
  {
    id: 'demo-3',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    title: 'Business bulk — office snacks',
    seller: '@OfficeNoshAU',
    authorId: 'demo_office_nosh',
    priceLabel: '$120 pack',
    blurb: 'B2B · invoice available',
    likes: 3400,
    growthVelocityScore: 1.08,
    watchTimeMsSeed: 640_000,
    categories: ['b2b', 'supplies'],
    region: 'AU_WIDE',
    commerce: { kind: 'buy_sell_listing', listingId: 'lst_1775627637728_yeg1wq1u' },
  },
  {
    id: 'fetch-promo-welcome',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    title: 'Same-day essentials on Fetch',
    seller: FETCH_DROPS_OFFICIAL_HANDLE,
    authorId: FETCH_DROPS_OFFICIAL_AUTHOR_ID,
    priceLabel: 'From $6',
    blurb: 'Official · Supplies + delivery zones',
    likes: 50200,
    growthVelocityScore: 1.0,
    watchTimeMsSeed: 5_000_000,
    categories: ['promo', 'supplies'],
    region: 'AU_WIDE',
    commerce: { kind: 'marketplace_product', productId: 'sup-drink-soft-case' },
    isOfficial: true,
    isSponsored: true,
  },
  // —— Live tab demo: `mediaKind: live_replay` — 70% community / 30% auction-seller mix in UI ——
  {
    id: 'demo-live-community-park',
    mediaKind: 'live_replay',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    title: 'Community live — weekend park meetup',
    seller: '@NeighbourhoodSEQ',
    authorId: 'demo_live_community_1',
    priceLabel: 'Live',
    blurb: 'Chat + local hangs',
    likes: 4200,
    growthVelocityScore: 1.28,
    watchTimeMsSeed: 890_000,
    categories: ['community'],
    region: 'SEQ',
  },
  {
    id: 'demo-live-community-makers',
    mediaKind: 'live_replay',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    title: 'Maker space tour — open desks',
    seller: '@MakersBrisbane',
    authorId: 'demo_live_community_2',
    priceLabel: 'Live',
    blurb: 'Community stream',
    likes: 3100,
    growthVelocityScore: 1.12,
    watchTimeMsSeed: 720_000,
    categories: ['community', 'services'],
    region: 'SEQ',
  },
  {
    id: 'demo-live-community-run',
    mediaKind: 'live_replay',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    title: 'Sunrise run club — Riverloop',
    seller: '@RiverRunClub',
    authorId: 'demo_live_community_3',
    priceLabel: 'Live',
    blurb: 'Everyone welcome',
    likes: 8800,
    growthVelocityScore: 1.35,
    watchTimeMsSeed: 1_100_000,
    categories: ['community'],
    region: 'SEQ',
  },
  {
    id: 'demo-live-community-food',
    mediaKind: 'live_replay',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    title: 'Food truck row — what’s cooking',
    seller: '@StreetEatsSEQ',
    authorId: 'demo_live_community_4',
    priceLabel: 'Live',
    blurb: 'Live from the lot',
    likes: 12500,
    growthVelocityScore: 1.18,
    watchTimeMsSeed: 1_400_000,
    categories: ['community', 'local_pickup'],
    region: 'SEQ',
  },
  {
    id: 'demo-live-community-open-mic',
    mediaKind: 'live_replay',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    title: 'Open mic night — community stage',
    seller: '@OpenMicSEQ',
    authorId: 'demo_live_community_5',
    priceLabel: 'Live',
    blurb: 'Performers welcome',
    likes: 5600,
    growthVelocityScore: 1.05,
    watchTimeMsSeed: 600_000,
    categories: ['community'],
    region: 'SEQ',
  },
  {
    id: 'demo-live-auction-vintage',
    mediaKind: 'live_replay',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    title: 'Auction live — vintage desk & lamp',
    seller: '@OfficeNoshAU',
    authorId: 'demo_office_nosh',
    priceLabel: 'Bidding open',
    blurb: 'Seller auction stream',
    likes: 2100,
    growthVelocityScore: 1.4,
    watchTimeMsSeed: 950_000,
    categories: ['b2b'],
    region: 'AU_WIDE',
    commerce: { kind: 'buy_sell_listing', listingId: 'lst_1775627637728_yeg1wq1u' },
    commerceSaleMode: 'auction',
  },
  {
    id: 'demo-live-auction-sneakers',
    mediaKind: 'live_replay',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    title: 'Seller auction — limited sneakers',
    seller: '@FetchSupply',
    authorId: 'demo_fetch_supply',
    priceLabel: 'Current bid',
    blurb: 'Auction seller live',
    likes: 15400,
    growthVelocityScore: 1.52,
    watchTimeMsSeed: 2_000_000,
    categories: ['supplies', 'promo'],
    region: 'SEQ',
    commerce: { kind: 'marketplace_product', productId: 'sup-drink-sparkling-12' },
    commerceSaleMode: 'auction',
  },
  {
    id: 'demo-live-auction-art',
    mediaKind: 'live_replay',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    title: 'Studio auction — prints & originals',
    seller: '@BrisbaneBasics',
    authorId: 'demo_brisbane_basics',
    priceLabel: 'Reserve met',
    blurb: 'Bid with the stream',
    likes: 3900,
    growthVelocityScore: 1.22,
    watchTimeMsSeed: 810_000,
    categories: ['community'],
    region: 'SEQ',
    commerce: { kind: 'buy_sell_listing', listingId: 'lst_1775627637728_yeg1wq1u' },
    commerceSaleMode: 'auction',
  },
]

/** What to wire server-side next (payments, fraud, real MAU, geo). */
export const DROPS_BACKEND_NEXT_STEPS = [
  'Persist reels, watch time, and likes in Postgres with idempotent events.',
  'Enforce globally unique @handle via server + index; block reserved names (Fetch, admin).',
  'Stripe Checkout for boost SKUs; store boost_window_start/end and tier.',
  'Targeting: save advertiser regions + categories; match to viewer prefs / IP region.',
  'Smart views: blend impressions, completion rate, and cohort size for estimates.',
  'Moderation queue for boosted + official slots; rate limits per account.',
] as const
